display: 0
debug: true
logFilePath: log.txt

health: # Healing configuration, all values in %
  healingPotionAt: 80
  manaPotionAt: 10
  rejuvPotionAtLife: 30
  rejuvPotionAtMana: 0
  mercHealingPotionAt: 80
  mercRejuvPotionAt: 20
  chickenAt: 20
  mercChickenAt: 0

bindings:
  potion1: 1
  potion2: 2
  potion3: 3
  potion4: 4

inventory:
  beltColumn1: heal # Allowed values: heal, mana, rejuv
  beltColumn2: heal # Allowed values: heal, mana, rejuv
  beltColumn3: rejuv # Allowed values: heal, mana, rejuv
  beltColumn4: mana # Allowed values: heal, mana, rejuv

character:
  difficulty: hell # Allowed values: normal, nightmare, hell
  useMerc: true

mapAssist:
  hostName: http://localhost:1111