display: 0
debug: true
logFilePath: log.txt

health: # Healing configuration, all values in %
  healingPotionAt: 80
  manaPotionAt: 10
  rejuvPotionAtLife: 30
  rejuvPotionAtMana: 0
  mercHealingPotionAt: 80
  mercRejuvPotionAt: 20
  chickenAt: 20
  mercChickenAt: 0

bindings:
  potion1: 1
  potion2: 2
  potion3: 3
  potion4: 4

  # Skills
  forceMove: e
  standStill: j
  swapWeapon: g
  teleport: f1
  tp: f8
  CTABattleCommand: d
  CTABattleOrders: s

  # Class specific bindings
  sorceress:
    blizzard: f2
    staticField: f3
    frozenArmor: f4

inventory:
  inventoryLock:
    - [1, 1, 1, 1, 1, 1, 1, 1, 0, 0] # 0: Item locked and won't be moved.
    - [1, 1, 1, 1, 1, 1, 1, 1, 0, 0] # 1: Item unlocked, it will be stashed, sold or dropped.
    - [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
    - [1, 1, 1, 1, 1, 1, 1, 1, 0, 0]

  beltColumns: # Amount of columns for each type of potion, sum of all should not be more than 4
    healing: 2
    mana: 1
    rejuvenation: 1
  beltRows: 4
  
character:
  difficulty: hell # Allowed values: normal, nightmare, hell
  useMerc: true
  useCTA: false
