pickupGold: true
minimumGoldToPickup: 1000

items:
  # Potions
  - superhealingpotion:
  - supermanapotion:
  - rejuvenationpotion:
  - superrejuvenationpotion:

  # Runes
  - elrune:
  - eldrune:
  - tirrune:
  - nefrune:
  - ethrune:
  - ithrune:
  - talrune:
  - ralrune:
  - ortrune:
  - thulrune:
  - amnrune:
  - solrune:
  - shaelrune:
  - dolrune:
  - helrune:
  - iorune:
  - lumrune:
  - korune:
  - falrune:
  - lemrune:
  - pulrune:
  - umrune:
  - malrune:
  - istrune:
  - gulrune:
  - vexrune:
  - ohmrune:
  - lorune:
  - surrune:
  - berrune:
  - jahrune:
  - chamrune:
  - zodrune:

  - amulet: {quality: unique}
  - ring: {quality: unique}
  - shako: {quality: unique} # Harlequin Crest